"""Aggregate benchmark results into bench/RESULTS.md, results.json and edits.csv."""
from __future__ import annotations

import csv
import math
from statistics import mean

from common import BENCH, NIGHTS, RESULTS_DIR, SKILLS, read_json, write_json

DEV_SKILLS = {"brand-guidelines"}  # used to write judge prompt v2 (PROTOCOL.md change 2)
CONFIGS = [("deterministic", "A: deterministic only"), ("judge_v1", "B1: + judge v1 (pre-registered)"),
           ("judge_v2", "B2: + judge v2 (default)")]
FLAGGED = {"review", "block"}


def wilson(k: int, n: int) -> str:
    if n == 0:
        return "n/a"
    z = 1.96
    p = k / n
    centre = (p + z * z / (2 * n)) / (1 + z * z / n)
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n)
    return f"{k}/{n} = {p:.0%} (95% CI {max(0, centre - half):.0%}–{min(1, centre + half):.0%})"


def collect() -> tuple[list[dict], dict]:
    rows, stats = [], {"proposed": 0, "unmatched": 0, "cost": {"skillopt": 0.0, "labels": 0.0, "guard": 0.0}, "noise": []}
    for name in SKILLS:
        d = RESULTS_DIR / name
        if not (d / "labels.json").exists() or not (d / "guard.json").exists():
            print(f"skipping {name}: missing labels or guard results")
            continue
        for night in range(1, NIGHTS + 1):
            nd = read_json(d / f"night{night}.json")
            stats["proposed"] += len(nd["edits"])
            stats["unmatched"] += sum(e["skillopt"] == "unmatched" for e in nd["edits"])
            stats["cost"]["skillopt"] += nd["cost_usd"]
        labels = read_json(d / "labels.json")
        stats["cost"]["labels"] += sum(labels["cost_usd"].values())
        g = read_json(d / "guard.json")
        stats["cost"]["guard"] += g["intent_cost_usd"] + g["guard_cost_usd"]
        verdicts = {n["night"]: n for n in g["nights"]}
        seen_noise = set()
        for e in labels["edits"]:
            if e["night"] not in seen_noise:
                stats["noise"].append(e["baseline_noise"])
                seen_noise.add(e["night"])
            v = verdicts[e["night"]]
            rows.append({
                "skill": name, "split": "dev" if name in DEV_SKILLS else "held-out",
                "night": e["night"], "index": e["index"], "op": e["op"],
                "skillopt": e["skillopt"], "noop": e["noop"], "harmful": e["harmful"],
                "baseline": round(e["baseline_mean"], 2), "edited": round(e["edited_mean"], 2),
                "delta": round(e["delta"], 2),
                **{c: v[c][e["index"]] for c, _ in CONFIGS},
                "content": e["content"],
            })
    return rows, stats


def section(rows: list[dict], title: str) -> tuple[list[str], dict]:
    live = [r for r in rows if not r["noop"]]
    harmful = [r for r in live if r["harmful"]]
    harmless = [r for r in live if not r["harmful"]]
    acc_harmful = [r for r in harmful if r["skillopt"] == "accepted"]
    acc_harmless = [r for r in harmless if r["skillopt"] == "accepted"]
    out = [f"### {title}", "",
           f"- Edits that changed the skill: {len(live)} ({len(rows) - len(live)} no-op edits excluded)",
           f"- Harmful by the behavioural label: {wilson(len(harmful), len(live))}",
           f"- SkillOpt gate accepted, among harmful edits: {wilson(len(acc_harmful), len(harmful))}",
           f"- SkillOpt gate accepted, among harmless edits: {wilson(len(acc_harmless), len(harmless))}",
           "", "| Guard config | Caught harmful (review or block) | Blocked harmful | Flagged harmless (false alarms) "
           "| Harmful that pass gate AND guard | Gate-accepted harmless kept |",
           "|---|---|---|---|---|---|"]
    js = {"n": len(live), "harmful": len(harmful), "skillopt_accepted_harmful": len(acc_harmful),
          "skillopt_accepted_harmless": len(acc_harmless), "configs": {}}
    for key, label in CONFIGS:
        caught = sum(r[key] in FLAGGED for r in harmful)
        blocked = sum(r[key] == "block" for r in harmful)
        false_flags = sum(r[key] in FLAGGED for r in harmless)
        slipped = sum(r[key] == "allow" for r in acc_harmful)
        kept = sum(r[key] == "allow" for r in acc_harmless)
        out.append(f"| {label} | {wilson(caught, len(harmful))} | {wilson(blocked, len(harmful))} | "
                   f"{wilson(false_flags, len(harmless))} | {slipped} of {len(acc_harmful)} | "
                   f"{wilson(kept, len(acc_harmless))} |")
        js["configs"][key] = {"caught": caught, "blocked": blocked, "false_flags": false_flags,
                              "slipped": slipped, "kept": kept}
    return out + [""], js


def main() -> None:
    rows, stats = collect()
    held = [r for r in rows if r["split"] == "held-out"]
    lines = ["# Benchmark results", "",
             "Generated by `bench/report.py`. The method, and every change made after the "
             "first run, are in [PROTOCOL.md](PROTOCOL.md). Every edit is listed in [edits.csv](edits.csv).", "",
             f"- Skills: {len({r['skill'] for r in rows})} ({', '.join(sorted({r['skill'] for r in rows}))})",
             f"- Edits proposed by SkillOpt: {stats['proposed']}, of which {stats['unmatched']} did not apply (unmatched)",
             f"- Baseline noise (difference between two scorings of the same unedited skill): "
             f"mean {mean(stats['noise']):.2f}, max {max(stats['noise']):.2f} points on 0–10. "
             "The harm threshold is 1.0.",
             f"- Cost: SkillOpt ${stats['cost']['skillopt']:.2f}, ground-truth labelling ${stats['cost']['labels']:.2f}, "
             f"guard ${stats['cost']['guard']:.2f}", ""]
    s1, j1 = section(held, "Held-out skills (headline)")
    s2, j2 = section(rows, "All skills, including the development skill")
    lines += s1 + s2
    harmful = [r for r in rows if r["harmful"]]
    if harmful:
        lines += ["### Every harmful edit", "", "| Skill | Night | SkillOpt | Δ score | A | B1 | B2 | Edit |", "|---|---|---|---|---|---|---|---|"]
        for r in sorted(harmful, key=lambda r: r["delta"]):
            text = r["content"].replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {r['skill']} | {r['night']} | {r['skillopt']} | {r['delta']:+.2f} | {r['deterministic']} | "
                         f"{r['judge_v1']} | {r['judge_v2']} | {text[:220]}{'…' if len(text) > 220 else ''} |")
        lines.append("")
    (BENCH / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    write_json(BENCH / "results.json", {"held_out": j1, "all": j2, "stats": stats})
    with open(BENCH / "edits.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
